services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - DISCORD_BOT_TOKEN
            - DISCORD_TEST_GUILD
            - RADIO_STREAM_URL
        volumes:
            - ${MUSIC_DIRECTORY}:/music
            - ${STREAMRIP_CONFIG_PATH}:/root/.config/streamrip/config.toml
    icecast:
        image: ghcr.io/libretime/icecast:2.4.4
        container_name: icecast
        restart: unless-stopped
        ports:
            - 8000:8000
        environment:
            - ICECAST_SOURCE_PASSWORD
            - ICECAST_RELAY_PASSWORD
            - ICECAST_ADMIN_PASSWORD
            - ICECAST_ADMIN_USERNAME
            - ICECAST_ADMIN_EMAIL
            - ICECAST_LOCATION
            - ICECAST_HOSTNAME
            - ICECAST_MAX_CLIENTS
            - ICECAST_MAX_SOURCES
        depends_on:
            - server
    liquidsoap:
        image: savonet/liquidsoap:v2.4.4
        container_name: liquidsoap
        entrypoint: ["liquidsoap", "/etc/liquidsoap/script.liq"]
        restart: unless-stopped
        ports:
            - 8001:8001
        environment:
            - ICECAST_SOURCE_PASSWORD
            - LIVE_SOURCE_PASSWORD
        volumes:
            - ./liquidsoap:/etc/liquidsoap:ro
            - ${MUSIC_DIRECTORY}:/music:ro
        depends_on:
            - icecast
